
import { GoogleGenAI, Type } from "@google/genai";
import { VerdictResponse, Grievance } from "../types";

export const getJudgeVerdict = async (grievance: Grievance): Promise<VerdictResponse> => {
  // Fix: Initializing GoogleGenAI with named parameter and direct environment variable access as per guidelines
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const systemInstruction = `
    You are 'Judge Grudge', the Chief Justice of the Supreme Court of Petty Grievances.
    Speak in dramatic HINGLISH.
    If 'isAppeal' is true, be 10x more aggressive and call the user 'Dheet' (stubborn).
    If a 'bribe' is provided, acknowledge it subtly in 'corruptionNote' (e.g., "Chai kaafi swadist thi, but kanoon andha hai... mostly").
    Take the 'witness' statement into account to make the judgment more specific.
    Goal: High drama, absurd historical precedents (pre-1900s), and funny 'moral damages'.
  `;

  const bribeContext = grievance.bribe ? `User has offered a bribe of: ${grievance.bribe}.` : "No bribe offered.";
  const witnessContext = grievance.witness ? `Witness Testimony: "${grievance.witness}".` : "No witnesses came forward.";
  const appealContext = grievance.isAppeal ? "THIS IS AN APPEAL. Be even more unhinged and final." : "This is a fresh case.";

  const prompt = `
    Case File: "${grievance.text}"
    ${witnessContext}
    ${bribeContext}
    ${appealContext}
    
    Deliver the FINAL VERDICT in Hinglish. Make it feel like a Mumbai session court drama.
  `;

  // Fix: Defined input parts with correct structure for text and optional image data
  const parts: any[] = [{ text: prompt }];
  if (grievance.image) {
    parts.push({
      inlineData: {
        mimeType: 'image/jpeg',
        data: grievance.image.split(',')[1] // Extract base64 part from data URL
      }
    });
  }

  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: { parts },
    config: {
      systemInstruction,
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          caseId: { type: Type.STRING },
          caseTitle: { type: Type.STRING },
          judgment: { type: Type.STRING },
          legalPrecedent: { type: Type.STRING },
          sentence: { type: Type.STRING },
          moralDamages: { type: Type.STRING },
          guiltMeter: { type: Type.NUMBER },
          dramaLevel: { type: Type.NUMBER },
          corruptionNote: { type: Type.STRING }
        },
        required: ["caseId", "caseTitle", "judgment", "legalPrecedent", "sentence", "moralDamages", "guiltMeter", "dramaLevel"]
      }
    }
  });

  // Fix: Directly accessed .text property of GenerateContentResponse as per documentation
  const resultText = response.text;
  if (!resultText) {
    throw new Error("No response generated by the model.");
  }

  return JSON.parse(resultText.trim()) as VerdictResponse;
};
